import sqlite3
import os
conn = sqlite3.connect(os.path.expanduser('~/Jules_mx/temp/jules_swarm_jobs.db'))
cursor = conn.cursor()
cursor.execute("INSERT INTO jobs (job_type, target_repo, instruction, status) VALUES (?, ?, ?, ?)", ('BASH', 'raj1', "python3 /home/misi/Jules_mx/scripts/vps_findings_analyst.py 'aichat-main/src/repl/mod.rs'", 'PENDING'))
cursor.execute("INSERT INTO jobs (job_type, target_repo, instruction, status) VALUES (?, ?, ?, ?)", ('BASH', 'raj2', "python3 /home/misi/Jules_mx/scripts/vps_findings_analyst.py 'chatbox-main/src/renderer/components/message-parts'", 'PENDING'))
cursor.execute("INSERT INTO jobs (job_type, target_repo, instruction, status) VALUES (?, ?, ?, ?)", ('BASH', 'raj3', "python3 /home/misi/Jules_mx/scripts/vps_findings_analyst.py 'AutoGPT-master/classic/original_autogpt/autogpt/app/ui/terminal'", 'PENDING'))
cursor.execute("INSERT INTO jobs (job_type, target_repo, instruction, status) VALUES (?, ?, ?, ?)", ('BASH', 'raj4', "python3 /home/misi/Jules_mx/scripts/vps_findings_analyst.py 'bloop-main/client/src/components/Chat.tsx'", 'PENDING'))
cursor.execute("INSERT INTO jobs (job_type, target_repo, instruction, status) VALUES (?, ?, ?, ?)", ('BASH', 'raj5', "python3 /home/misi/Jules_mx/scripts/vps_findings_analyst.py 'open-webui-main/backend/apps/webui/routers/chat.py'", 'PENDING'))
cursor.execute("INSERT INTO jobs (job_type, target_repo, instruction, status) VALUES (?, ?, ?, ?)", ('BASH', 'raj6', "python3 /home/misi/Jules_mx/scripts/vps_findings_analyst.py 'aider-main/aider/io.py'", 'PENDING'))
cursor.execute("INSERT INTO jobs (job_type, target_repo, instruction, status) VALUES (?, ?, ?, ?)", ('BASH', 'raj7', "python3 /home/misi/Jules_mx/scripts/vps_findings_analyst.py 'langchain-master/libs/cli/langchain_cli/utils/terminal.py'", 'PENDING'))
cursor.execute("INSERT INTO jobs (job_type, target_repo, instruction, status) VALUES (?, ?, ?, ?)", ('BASH', 'raj8', "python3 /home/misi/Jules_mx/scripts/vps_findings_analyst.py 'gemini-cli-main/src/ui/chat.rs'", 'PENDING'))
conn.commit()
conn.close()
print('Gemini alapú elemző feladatok kiosztva!')